# ./pnpm-workspace.yaml
packages:
  # all packages in subdirs of packages/
  - "packages/*"
  # root directory
  # - "."
  # exclude packages that are inside test/ directories
  # - "!**/test/**" # '!' means exclude
